version: "3"
networks:
  grafana-network:
    name: grafana-net
  home-network:
    name: home-network
services:
  loki:
    image: grafana/loki:3.5.5
    container_name: loki
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped
    user: "${UID}"
    volumes:
      - ${PWD}/loki-config/local-config.yml:/etc/loki/local-config.yml:ro
      - ${PWD}/volume-loki:/loki:rw
    networks:
      - grafana-network
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    user: "${UID}"
    command: --config.file=/prometheus-config.yml
    volumes:
      - ${PWD}/prometheus-config/prometheus.yml:/prometheus-config.yml:ro
      - ${PWD}/volume-prometheus:/prometheus:rw
    networks:
      - grafana-network
      - home-network
  grafana:
    image: grafana/grafana:11.5
    container_name: grafana
    user: "${UID}"
    volumes:
      - ${PWD}/grafana-config/grafana-provisioning.yml:/etc/grafana/provisioning/datasources/grafana-provisioning.yml:ro
      - ${PWD}/volume-grafana:/var/lib/grafana:rw
    networks:
      - grafana-network
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
  grafana-traefik:
    image: traefik:v3.5.2
    container_name: grafana-traefik
    volumes:
      - ${PWD}/traefik-config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${PWD}/traefik-config/traefik-routing.yml:/traefik-routing.yml:ro
      - ${PWD}/traefik-config/digestUsers.txt:/digestUsers.txt:ro
    networks:
      - grafana-network
    ports:
      - "7070:7070"
    depends_on:
      grafana:
        condition: service_started
