version: "3"
networks:
  grafana-network:
services:
  loki:
    image: grafana/loki:3.5.5
    container_name: loki
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped
    volumes:
      - ${PWD}/loki-config/local-config.yml:/etc/loki/local-config.yml:ro
      - ${PWD}/volume-loki:/loki:rw
    networks:
      - grafana-network
  grafana:
    image: grafana/grafana:11.5
    container_name: grafana
    user: $UID
    volumes:
      - ${PWD}/volume-grafana:/var/lib/grafana
      - ${PWD}/grafana-config/grafana-provisioning.yml:/etc/grafana/provisioning/datasources/grafana-provisioning.yml
    networks:
      - grafana-network
    depends_on:
      loki:
        condition: service_started
  treaefik:
    image: traefik:v3.5.2
    container_name: traefik
    volumes:
      - ${PWD}/traefik-config/traefik.yml:/etc/traefik/traefik.yml
      - ${PWD}/traefik-config/traefik-routing.yml:/traefik-routing.yml
    networks:
      - grafana-network
    ports:
      - "7070:7070"
    depends_on:
      grafana:
        condition: service_started
