version: "3"
networks:
  grafana-network:
services:
  loki:
    image: grafana/loki:3.5.5
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped
    volumes:
      - ${PWD}/volume-loki:/etc/loki
    networks:
      - grafana-network
  grafana:
    image: grafana/grafana:11.5
    restart: unless-stopped
    user: $UID
    volumes:
      - ${PWD}/volume-grafana:/var/lib/grafana
    networks:
      - grafana-network
  treaefik:
    image: traefik:v3.5.2
    volumes:
      - ${PWD}/volume-traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${PWD}/volume-traefik/traefik-routing.yml:/traefik-routing.yml
    networks:
      - grafana-network
    ports:
      - "7070:7070"
    depends_on:
      loki:
        condition: service_started
      grafana:
        condition: service_started
